os/hal/ports/STM32/STM32H7xx/hal_lld.h
@tridge - this was causing my build to fail when I specified "MCU STM32H7xx STM32H753xx" in my new hwdef.dat file.
=> STM32: fixed and separated H7 Configuration-related checks for H743/H753

os/hal/ports/STM32/LLD/SPIv1/hal_spi_lld.c, os/hal/ports/STM32/LLD/SPIv2/hal_spi_lld.c, os/hal/ports/STM32/LLD/SPIv3/hal_spi_lld.c
an electrical glitch on a STM32F765xx can cause FIFO de-sync where
unexpected bytes appear in the receive FIFO. When that happens we
reset the peripheral completely using the RCC. Note that just draining
the bytes is not effective
=> STM32: check for FIFO de-sync in SPIv2 and reset peripheral

os/hal/include/hal_i2c.h, os/hal/ports/STM32/LLD/I2Cv1/hal_i2c_lld.c, os/hal/ports/STM32/LLD/I2Cv1/hal_i2c_lld.h, os/hal/ports/STM32/LLD/I2Cv2/hal_i2c_lld.c, os/hal/ports/STM32/LLD/I2Cv2/hal_i2c_lld.h, os/hal/ports/STM32/LLD/I2Cv3/hal_i2c_lld.c, os/hal/ports/STM32/LLD/I2Cv3/hal_i2c_lld.h
this adds a limit on the number of interrupts allowed per transaction
for I2C peripherals on STM32. It is meant to prevent any possibility
of an interrupt storm due to a badly behaving peripheral which
generates an interrupt which isn't properly acknowledged or cannot be
acknowledged
=> STM32-I2C: added optional ISR limit per transaction

os/hal/ports/STM32/LLD/TIMv1/hal_pwm_lld.c
this restriction is not needed, and results in timing choices which
don't produce the best match for a desired bit rate
=> TIMv1: removed restriction on clock setting for pwm driver

os/hal/osal/rt/osal.h
This is required so that we use print assertion failure messages to a GPIO pin
=> Allow osalDbgAssert to be redefined

os/rt/include/chschd.h, os/rt/include/chsys.h, os/rt/include/chthreads.h
Giovanni has fixed this upstream more comprehensively. For now suppressing the warning is the simplest thing to do.
=> ChibiOS: suppress statistics warnings

ext/fatfs/source/ff.c
This solves the issue of builds breaking with -O3
=> fatfs: halt loop as index hits 0

os/various/fatfs_bindings/fatfs_syscall.c
=> fatfs: fixed use of malloc in f_mkdir()

ext/fatfs/source/ff.c
the old value exceeded the maximum DMA allocation on some boards, and
was the underlying cause of the mkdir failure on Pixhawk1
=> ff: lower MAX_MALLOC to 2048

os/hal/ports/STM32/LLD/I2Cv3/hal_i2c_lld.c
this allows for non-DMA I2C on H7
=> I2Cv3: fixed non-DMA build

os/hal/ports/STM32/LLD/ADCv4/hal_adc_lld.c
There is an addition of RCC reset for ADC, which causes default CCR settings to reset.
=> Fix ADC Dual mode operation

os/hal/ports/STM32/LLD/TIMv1/hal_pwm_lld.c, os/hal/ports/STM32/STM32H7xx/stm32_registry.h
* This resolves assertion detected while running on H7, ability to disable knowledge of M4 chips is needed for now, as we do clock resets before enabling them, there's no support for running on M4 right now anyways so ignoring the checks is just the best way for now.
* Other assert I hit is with NeoPixel setup where we don't get whole number out of target frequency and Timer clock.
=> Fixes for assertion fails

os/hal/ports/STM32/STM32H7xx/hal_lld.c
init of the top bit can lead to memory corruption in SRAM1 on H757, likely due to an issue with write-back cache
=> STM32: avoid initialising top bit of AHB1 RCC on H7

os/hal/ports/STM32/LLD/TIMv1/hal_eicu_lld.c, os/hal/ports/STM32/LLD/TIMv1/stm32_tim1.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim12.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim13.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim14.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim15.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim16.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim17.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim1_15_16_17.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim1_16_17.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim1_9_10_11.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim1_shared.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim2.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim20.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim21.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim22.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim3.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim3_4.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim4.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim5.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim6.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim7.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim8.inc, os/hal/ports/STM32/LLD/TIMv1/stm32_tim8_12_13_14.inc
The port of the 3rd-party EICU code missed some ISRs on some chips.
This is essentially a copy and paste of the ICU architecture for EICU
=> TIMv1: missing EICU ISRs

os/hal/ports/STM32/LLD/ADCv4/hal_adc_lld.c
For some reason while using ADC Dual mode the samples from ADC2 are getting shifted in order in memory, starting of as correct and then misbehaving almost immediately. The issue goes away when using interleaved sampling instead of simultaneous. So for now we can select interleaved sampling for Dual mode operation in ardupilot.
=> ADCv4: add support to select ADC12 DUAL operation mode

os/hal/src/hal_mmc_spi.c
MMC SPI would only ever read 512 bytes
=> hal_mmc_spi: fix multi-block reads

os/common/startup/ARMCMx/compilers/GCC/crt1.c
Cherry-pick of the dcache/icache fixes that are required to make ram execution reliable
=> ARMCMx: flush data and memory cache after updating ram init areas

os/hal/src/hal_mmc_spi.c
needed to ensure we get DMA lock before the bus lock, so we don't deadlock with another device on the same bus
=> mmc_spi: added bus acquire hooks

ext/fatfs/source/ffsystem.c, os/various/fatfs_bindings/fatfs_syscall.c
=> FATFS: disable ff_memalloc function for ArduPilot

os/hal/ports/STM32/LLD/MACv2/hal_mac_lld.c, os/various/lwip_bindings/lwipthread.c
This allows for ardupilot to dynamically allocate buffers and mark the region with correct flags. This way we don't waste an entire ram region even when networking is disabled.
=> Add support for defining buffers dynamically

os/hal/ports/STM32/LLD/MACv2/hal_mac_lld.c
a shift of 11 is correct for MAVv1. In v2 it is 21, ETH_MACMDIOAR_PA_Pos
=> MAVv2: fixed shift of BOARD_PHY_ADDRESS
